[project]
name = "rsrch-data"
version = "0.1.0"
description = "DVC-tracked datasets repo & data loaders"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "anyio>=4.14.0",
    "datatrove>=0.3.0",
    "dbfread>=2.0.7",
    "h5py>=3.15.1",
    "hf-xet>=1.2.0",
    "multivolumefile>=0.2.3",
    "mwparserfromhell>=0.7.2",
    "numpy<2",
    "pandas>=2.3.3",
    "pillow>=12.0.0",
    "py7zr>=1.1.3",
    "pyarrow>=22.0.0",
    "pycocotools>=2.0.10",
    "pydantic>=2.12.3",
    "rasterio>=1.4.4",
    "rich>=15.0.0",
    "ruamel-yaml>=0.18.16",
    "tokenizers>=0.23.1",
    "tyro>=1.0.8",
]

[build-system]
requires = ["uv_build>=0.8.22,<0.9.0"]
build-backend = "uv_build"

[tool.uv]
package = true

[tool.uv.sources]
fiftyone-db = { path = "ext/fiftyone_db-1.4.1.tar.gz" }

[dependency-groups]
dev = [
    "huggingface-hub>=1.0.1",
    "ipykernel>=7.0.1",
    "jupyter>=1.1.1",
    "lxml>=6.0.2",
    "scipy>=1.15.3",
    "dvc-s3>=3.2.2",
    "kaggle>=1.7.4.5",
    "pre-commit>=4.5.1",
    "ruff>=0.12.12",
    "fiftyone>=1.16.0",
    "rerun-sdk>=0.23.1",
    "gdown>=6.1.0",
    "setuptools>=66",
    "fiftyone-db",
    "trimesh>=4.12.2",
]

[tool.black]
line-length = 88

[tool.ruff]
line-length = 88
indent-width = 4
target-version = "py310"
exclude = ["src/rsrch_data/_colmap/*"]

[tool.ruff.format]
docstring-code-format = true
exclude = ["ext/*", "src/rsrch_data/_colmap/*"]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "PLR0913", # Too many arguments
    "INP001",  # ... is part of an implicit namespace package.
    "RET505",  # Unnecessary `else` after `return` statement
    "ANN202",  # Missing return type annotation for private function
    "ANN401",  # Dynamically typed expressions (typing.Any) are disallowed
    "FBT",     # Flake Boolean Traps
    "PLR2004", # Magic value used in comparison
    "ARG002",  # Unused method argument: `key`
    "D105",    # Missing docstring in magic method
    "ANN204",  # Missing return type annotation for special method
    "RET504",  # Remove unnecessary assignment
    "T201",    # `print` found
    # Conflicts
    "D203",   # one-blank-line-before-class — conflicts with D211 (no-blank-line-before-class)
    "D213",   # multi-line-summary-second-line — conflicts with D212 (multi-line-summary-first-line)
    "COM812", # missing-trailing-comma — conflicts with ruff formatter
]
