stages:
  cifar10:
    deps:
      - archives/cifar-10-python.tar.gz
    cmd: tar xf archives/cifar-10-python.tar.gz
    outs:
      - cifar-10-batches-py
  cifar100:
    deps:
      - archives/cifar-100-python.tar.gz
    cmd: tar xf archives/cifar-100-python.tar.gz
    outs:
      - cifar-100-python
